paratranz_id: 7760
projects:
  Modern:
    repo: https://github.com/GregTechCEu/GregTech-Modern
    file_path: src/generated/resources/assets/gtceu/lang/en_us.json
    paratranz_name: zh_cn_packed.json
    tranlated_name: zh_cn.json
    base: 1.20.1
    versions:
      1.20.1:
        branch: 1.20.1
        paratranz_id: 1024741
      '1.21':
        branch: '1.21'
        paratranz_id: 2054341
  CEu:
    repo: https://github.com/GregTechCEu/GregTech
    file_path: src/main/resources/assets/gregtech/lang/en_us.lang
    paratranz_name: zh_cn.lang.json
    tranlated_name: zh_cn.lang
    versions:
      '1.12':
        branch: master
        paratranz_id: 1120814
